### ISSUE TITLE
UI alpha version

### ISSUE THREAD

**Issue by dev01metatech** [Middlecon/DBImport#100]
Morning,
I have downloaded the tar version of DBImport and installed it. I am in need of UI testing and could you please give me the document and install process for UI

**Comment by BerryOsterlund** [comment]
The original web-UI that I worked on a long time ago is dropped. What I'm focusing right now is a python based client that will communicate with a DBImport REST server. So far, the functionallity is very limited and not even the basic functionallity is there. Like adding a table for importing or changing configuration is still not working. But as soon as the basic functions is there, I will make a release of that code as well. Sorry that I have nothing else to give you at this stage.
