### ISSUE TITLE
atlas discovery  for new schema and database  

### ISSUE THREAD

**Issue by dev01metatech** [Middlecon/DBImport#81]
I have existing JDBC connection and able to import the data into  apache atlas using discovery capabilities but  when I tried to import the new schema using new Database alias for same server. I get following and I believe it should create new entity for this as part of discovery process. it should not complain that  {"errorCode":"ATLAS-404-00-009","errorMessage":"Instance rdbms_db with unique attribute {qualifiedName=hive_metastore@e2eadmin2:3306} does not exist"}

1. I create new JDBC connection alias e2eadmin_all_mysql  an :   hive_metastore@e2eadmin:3306 
2. trying to discover new database/schema into atlas 
3. I get following error message 
4. following is screenshot of JDBC connection

![jdbc_connection_dbimports_atlas_troubleshooting](https://user-images.githubusercontent.com/72705041/99643394-9d35d800-2a1a-11eb-92f9-5e6770b368de.png)

/manage -v --discoverAtlasRdbms -a e2eadmin_all_mysql

DEBUG connectToJDBC -   self.jdbc_driver = com.mysql.cj.jdbc.Driver
DEBUG connectToJDBC -   self.jdbc_url = jdbc:mysql://e2eadmin2:3306/hive_metastore
DEBUG connectToJDBC -   self.jdbc_classpath_for_python = /metatech/dbimport/driver/mysql/mysql-connector-java-8.0.22.jar
DEBUG getJDBCtablesAndViews - SQL Statement executed: select '-', table_name from INFORMATION_SCHEMA.tables where table_schema = 'hive_metastore' order by table_name
DEBUG getJDBCtablesAndViews - Executing common_config.getJDBCtablesAndViews() - Finished
DEBUG atlasGetData - Executing common_config.atlasGetData()
DEBUG atlasCommunicate - Executing common_config.atlasCommunicate()
DEBUG _new_conn - Starting new HTTP connection (1): localhost:21000
DEBUG _make_request - http://localhost:21000 "GET /api/atlas/v2/entity/uniqueAttribute/type/rdbms_db?minExtInfo=true&attr:qualifiedName=hive_metastore@e2eadmin2:3306 HTTP/1.1" 404 None
DEBUG atlasCommunicate - Atlas statusCode = 404
DEBUG atlasCommunicate - Atlas data = {"errorCode":"ATLAS-404-00-009","errorMessage":"Instance rdbms_db with unique attribute {qualifiedName=hive_metastore@e2eadmin2:3306} does not exist"}
DEBUG atlasCommunicate - Executing common_config.atlasCommunicate() - Finished
WARNING discoverAtlasRdbms - Request from Atlas when updating source schema was 404.
WARNING discoverAtlasRdbms - {"errorCode":"ATLAS-404-00-009","errorMessage":"Instance rdbms_db with unique attribute {qualifiedName=hive_metastore@e2eadmin2:3306} does not exist"}
(venv) root@e2eadmin2:/metatech/dbimport/DBImport/bin#

**Comment by dev01metatech** [comment]
I was able to spend time on this and error message is mis-leading.  above error happens because there is database but no table  existing within the database. I was able to recreate the issue multiple time.

**Comment by BerryOsterlund** [comment]
Great news. That will make it easier to find the problem. Thanks. 

Btw. For the last week or so, I have been working with improving the speed of the atlas discovery process. I hope I can submit the new functions during next week (home sick and cant work as much as I want on this). It will improve the speed for discovering a database with many times over. As soon as I'm done with that code, I will make a fix for this problem.

**Comment by dev01metatech** [comment]
Thank you - I will close this issue.
